### ISSUE TITLE
Restore data issues

### ISSUE THREAD

**Issue by tabbi-yellow** [juanjoGonDev/fastypest#372]
Should be from 1 not from 0 `SELECT COALESCE(MAX(id), 1) FROM "XXX"))`
Secondly not all tables have id column

**Comment by juanjoGonDev** [comment]
I’ve updated the logic to now detect columns with auto-increment, so it no longer relies on the id column. My mistake for only checking that column, as it might not always be present.

It should be working now. Thanks for pointing out the issue, and sorry for the delay.
