### ISSUE TITLE
install fails when in a subproject of a monorepo

### ISSUE THREAD

**Issue by Nijusan** [juanjoGonDev/fastypest#406]
hi, i used this tool in my monorepo with a vuejs /frontend project and a nestjs /backend project. now trying to install fastypest in my /backend fails, because .git only exists on folder top:

» » npm i -D fastypest
npm error code 1
npm error path /.../backend/node_modules/fastypest
npm error command failed
npm error command sh -c husky install
npm error husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)

why wants this project now to install husky for pre-commits?

**Comment by juanjoGonDev** [comment]
Thank you for reporting the bug. The request for Husky upon installation is my fault, I apologize, it was a bad configuration in the package.json. Now you should be able to use it without any problem.
